//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week4.EF
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Customer
    {
        public Customer()
        {
            this.Product_Customer = new HashSet<Product_Customer>();
        }
    
        public int ID { get; set; }

        [Required]
        [StringLength(110, ErrorMessage = "Customer name cannot exceed 110 characters.")]
        public string Name { get; set; }

        [Required]
        [RegularExpression(@"^[a-zA-Z0-9.]+@gmail\.com$", ErrorMessage = "Invalid email address format.")]
        public string Email { get; set; }

        [RegularExpression(@"^\+?[0-9]{10,15}$", ErrorMessage = "Invalid phone number format.")]
        public string Phone { get; set; }

        [StringLength(250, ErrorMessage = "Address cannot exceed 250 characters.")]
        public string Address { get; set; }
        public System.DateTime DateJoined { get; set; }
    
        public virtual ICollection<Product_Customer> Product_Customer { get; set; }
    }
}
